name: Publish Docker image
on:
  push: {branches: master}
jobs:
  test_main_docker:
    name: Test and Run the docker
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Check environment
        run: |
          ls
          pwd
      - name: Build Dockerfile
        run: docker build -t mykuromoji .
      - name: Run Dockerfile with node
        run: docker run mykuromoji /bin/bash -c 'node /home/app/tryme.js'

