name: Publish Docker image
on:
  push: {branches: main}
jobs:
  test_main_docker:
    name: Test and Run the docker
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Check environment
        run: |
          ls
          pwd
      - name: Build Dockerfile
        run: docker build -t mykuromoji .
      - name: Run Dockerfile with node
        run: docker run mykuromoji /bin/bash -c 'node /home/app/tryme.js'
      - name: Copy .gz files
        run: |
          docker create -ti --name dummy mykuromoji /bin/bash
          docker cp dummy:/home/lib/kuromoji.js/dict/ .
          docker rm -f dummy
      - name: Check artifacts
        run: |
          ls
          pwd
